### ISSUE TITLE
conda ptitprince 0.2.5 not working with seaborn 0.12.1

### ISSUE THREAD

**Issue by lopezavila85** [pog87/PtitPrince#34]
Hi,

When importing ptitprince 0.2.5 in an Anaconda environment with seaborn 0.12.1 I get the following error.
May I use another seaborn version? Thanks in advance.

```
Name                    Version                   Build  Channel
seaborn                   0.12.1               hd8ed1ab_0    conda-forge
seaborn-base          0.12.1             pyhd8ed1ab_0    conda-forge

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[8], line 13
     10 plt.rcParams["figure.figsize"] = (12, 10)
     12 #!pip install -q ptitprince
---> 13 import ptitprince as pt 
     15 size = 1000
     16 # central peak

File C:\software\anaconda3\envs\ox\lib\site-packages\ptitprince\__init__.py:1
----> 1 from .PtitPrince import *

File C:\software\anaconda3\envs\ox\lib\site-packages\ptitprince\PtitPrince.py:20
     16 #from seaborn.external.six import string_types
     17 #from seaborn.external.six.moves import range
     19 from seaborn import utils
---> 20 from seaborn._core import categorical_order
     21 from scipy.stats import iqr
     22 from seaborn.utils import remove_na

ImportError: cannot import name 'categorical_order' from 'seaborn._core' (C:\software\anaconda3\envs\ox\lib\site-packages\seaborn\_core\__init__.py)
```

**Comment by pirao** [comment]
I also encountered the same problem

**Comment by leorrose** [comment]
Unfortunately, I also encountered the same problem with seaborn `0.12.2`.

I managed to solve this problem by downgrading seaborn version to `0.11.2`.

Looking at the code and the changes in seaborn from 0.11.2 it seems the issue occurs because of the the change in location of `from seaborn._core import categorical_order` to from `seaborn._core.rules import categorical_order`.

**Comment by pog87** [comment]
duplicate of #25

**Comment by wi11iamk** [comment]
Hello. I have encountered the same problem with seaborn 0.12.2. I see the issue was worked around by downgrading to 0.11.2. Has a more stable solution been implemented for the current version of Seaborn?
