### ISSUE TITLE
seaborn 0.12 changes internal API

### ISSUE THREAD

**Issue by ajparsons** [pog87/PtitPrince#25]
The new release of seaborn changes some of the internals that this depends on.

`_CategoricalScatterPlotter` is gone and can't on a quick look see what to replace it with.

Recommend pinning the requirements.txt to seaborn==0.11 in the meantime?

**Comment by pog87** [comment]
Just pinned. 
I'll keep this open to remind this is a temporary fix.

thank you

**Comment by HernandoMV** [comment]
Great package! Will save me lots of time. Any plans for making it work with seaborn 0.12?

**Comment by filippoferrari** [comment]
Hi, is there any update on making the package compatible with seaborn > 0.12? 
Thanks!

**Comment by eroell** [comment]
@filippoferrari also interested :)

**Comment by AMDeitsch** [comment]
I tried to use this package a while ago and had some frustrations with getting it to format the way I wanted. I've got a Jupyter Notebook that I can clean up from my individual data and upload it in the near future—not as fancy as a package to call on, but should get the job done and be easily modifiable. Also, note that I used histograms for my clouds because it suited our data better.

![Screenshot_20240507_132003_Gallery.jpg](https://github.com/pog87/PtitPrince/assets/102323536/3e1f6d4c-8f5d-4d64-bc00-156d9e3ba87d)

**Comment by Carl-McBride-Ellis** [comment]
+1: The Kaggle environment now uses seaborn 0.12.2 so doing something about the
`ImportError: cannot import name '_CategoricalScatterPlotter' from 'seaborn.categorical'` 
would be fantastic.

All the best,
carl

**Comment by jwdebelius** [comment]
Wondering if there's any update on pushing this to seaborn >= 0.12?

Thanks!

**Comment by lubitelpospat** [comment]
Hi folks, have there been any updates on making this work with newer versions of seaborn?

**Comment by lcalix** [comment]
Same I'm in a hell of library incompatibility right now :/ are there some requirements somewhere ? Like complete ones ?

**Comment by syntactic** [comment]
@lcalix @lubitelpospat @jwdebelius I have a branch with support for seaborn 0.13.2 pending a pull request approval. 
https://github.com/syntactic/PtitPrince/tree/modernization_packaging_testing
Feel free to use it until it's been approved and let me know if you run into any issues.
